version: '2'

services:

  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
     - db
    volumes:
     - ./php/:/var/www/html/
    ports:
     - "8100:80"
  db:
    image: mysql
    container_name: sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 9090:80
    volumes:
     - /sessions
    external_links:
     - sql:db
